# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: manakal
# "service" is the name of this project. This will also be added to your AWS resource names.
service: durableDemo
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  greet:
    handler: handler.hello
    events:
      - httpApi:
          path: /greet
          method: get
  anotherGreet:
    handler: anotherGreet.anotherGreet
    events:
      -  httpApi:
           path: /greet
           method: post
      